name: Nolan Conaway
author: Nolan Conaway
permalink: /blog/:year/:title
github: [metadata]
 

# Configure Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

gems:
  - jekyll-sitemap
  - jekyll-feed


# default info
title: Nolan Conaway
description: Nolan Conaway's personal website and blog.
keywords: cognitive, data, science
author: Nolan Conaway



